# Generated by Django 4.2 on 2023-05-10 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='noticia',
            fields=[
                ('idnoticia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_periodista', models.CharField(max_length=60)),
                ('titulo_noticia', models.TextField()),
                ('titular_noticia', models.TextField()),
                ('cuerpo_noticia', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webCaosNew.categoria')),
            ],
        ),
    ]
