# Generated by Django 4.2 on 2023-05-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCaosNew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
    ]
