# Generated by Django 4.2 on 2023-06-20 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webCaosNew', '0006_alter_noticia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='comentario',
            field=models.TextField(default='S/C'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='precio',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='noticia',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noticia',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
