# Generated by Django 4.1.5 on 2023-06-20 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webCaosNew', '0007_noticia_comentario_noticia_precio_noticia_publicar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('idGaleria', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='foto')),
                ('Noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webCaosNew.noticia')),
            ],
        ),
    ]
