# Generated by Django 4.2 on 2023-06-21 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webCaosNew', '0008_galeria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='Noticia',
            new_name='noticia',
        ),
    ]
