# Generated by Django 4.2 on 2023-06-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCaosNew', '0009_rename_noticia_galeria_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='foto',
            field=models.ImageField(upload_to='fotos'),
        ),
    ]
