# Generated by Django 4.2.1 on 2023-06-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCaosNew', '0011_objcarrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objcarrito',
            name='idobjeto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
