# Generated by Django 4.2.1 on 2023-06-25 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webCaosNew', '0012_alter_objcarrito_idobjeto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objcarrito',
            old_name='imagen',
            new_name='foto',
        ),
    ]
